title: "Documentation | Phish4All"
description: 
theme: just-the-docs

color_scheme: dark
mermaid:
  version: "9.1.3"
nav_enabled: true
logo: "assets/images/logo.svg"
favicon_icon: "assets/images/logo.ico"
