title: "Phish4All"
description: 
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

color_scheme: dark
mermaid:
  version: "9.1.3"
nav_enabled: true
logo: "assets/images/logo_title.svg"
favicon_ico: "assets/images/logo.ico"
kramdown:
  footnote_nr: 0
